# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mobile Chat App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mobile Chat App

end
